###
GET http://localhost:8080/books/1
Accept: application/cs.miu.edu-v2+json

###
GET http://localhost:8080/books
X-API-VERSION: 2

###
GET http://localhost:8080/v1/books

###
GET http://localhost:8080/books?version=1

###
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Spring Framework",
  "isbn": 123456789,
  "price": 50.0
}

###
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Updated Title",
  "isbn": 987654321,
  "price": 45.0
}

###
DELETE http://localhost:8080/books/1